sudo: true
language: python

matrix:
  include:
    - os: linux
      env: 
      - PYTHON_VER="2.7"
    - os: linux
      env:
      - PYTHON_VER="3.4"
    - os: linux
      env:
      - PYTHON_VER="3.5"
    - os: osx
      language: generic
      env:
      - PYTHON_VER="3.5"

script:
  - ci/setup.sh

