language: python

python:
  - "2.7"
  - "3.4"

env:
  - CUDA=6.5

before_install:
  # install cuda
  - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_${CUDA}-14_amd64.deb
  - travis_retry sudo dpkg -i cuda-repo-ubuntu1204_${CUDA}-14_amd64.deb
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -y cuda-${CUDA/./-}
  - travis_retry sudo apt-get install -y cuda-drivers cuda-core-${CUDA/./-} cuda-cudart-dev-${CUDA/./-}
  - travis_retry sudo apt-get clean
  - export CUDA_HOME=/usr/local/cuda-${CUDA}
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - export PATH=${CUDA_HOME}/bin:${PATH}
  - nvcc --version
  # use conda for quicker numpy installation
  - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  # create virtual env
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy nose
  - pip install flake8 hacking
  # pycuda installation
  - travis_retry wget --no-check-certificate https://pypi.python.org/packages/source/p/pycuda/pycuda-2014.1.tar.gz
  - tar xvfz pycuda-2014.1.tar.gz
  - cd pycuda-2014.1
  - python configure.py --cuda-root=${CUDA_HOME}
  - make -j 4
  - python setup.py install
  - cd ~
  - pip install scikits.cuda Mako six
  - python setup.py install

script:
  - nosetests
  - flake8 chainer/**/*.py tests/**/*.py examples/**/*.py --exclude=libcudnn.py
